name: 'Live Update'
on:
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch:

jobs:
  run_job:
    runs-on: ubuntu-22.04
    permissions:
      contents: write  # 核心写权限，必须保留
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 1 
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5.2.0
        with:
          python-version: '3.10'
          
      - name: 安装Python依赖
        run: |
          python -m pip install --upgrade pip
          pip install opencc-python-reimplemented

      - name: Run Python script
        run: |
          rm -f live.txt live.m3u live_lite.txt live_lite.m3u others.txt
          python main.py

      - name: 暂存文件
        run: git add live.txt live.m3u live_lite.txt live_lite.m3u others.txt
        continue-on-error: true
          
      - name: 拉取最新代码并提交推送
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          
          if git diff --cached --name-only | grep -q .; then
            git fetch origin main
            git commit -m "Live Update: $(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M') (CST)"
            git push origin HEAD:$GITHUB_REF_NAME --force
            echo "✅ 拉取最新代码并强制推送完成"
          else
            echo "ℹ️ 无文件变更，跳过提交和推送"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
